version: '3.8'


services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DATABASE=${DB_NAME}
      - DB_DIALECT=${DB_DIALECT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AUTH_TOKEN=${AUTH_TOKEN}
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE:     ${DB_NAME}
      MYSQL_USER:         ${DB_USER}
      MYSQL_PASSWORD:     ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
  



